# Generated by Django 4.2.6 on 2023-11-07 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
