# Generated by Django 4.2.6 on 2023-11-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_persona_domicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='no_calle',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
